"""
Report Exporter Tool - saves a markdown report to the reports/ directory.
  - @tool with file I/O: tools can do more than call LLMs - they can write files
  - LLM chain via LCEL pipe: prompt | llm → generates the report content
"""

import os
from datetime import datetime
from langchain_core.tools import tool
from langchain_core.prompts import PromptTemplate
from langchain_core.output_parsers import StrOutputParser
from src.config import llm

REPORTS_DIR = os.path.join(os.path.dirname(__file__), "..", "..", "reports")

report_prompt = PromptTemplate(
    input_variables=["topic", "context"],
    template="""Create a well-structured markdown report on the following topic.

Topic: {topic}

Context/Notes: {context}

Format the report with:
- A title (# heading)
- An executive summary
- Key points as bullet lists
- A conclusion

Keep it concise and professional."""
)


@tool
def export_report(topic: str, context: str = "No additional context provided") -> str:
    """Generate a structured markdown report on a topic and save it to a file.
    Provide 'topic' and optionally 'context' with any notes or research to include."""

    # Chain: prompt -> LLM ->  parse as plain string
    chain = report_prompt | llm | StrOutputParser()
    report_content = chain.invoke({"topic": topic, "context": context})

    # add metadata header
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M")
    header = f"-\nGenerated by Neuron | {timestamp}\nTopic: {topic}\n-\n\n"
    full_report = header + report_content

    # save
    os.makedirs(REPORTS_DIR, exist_ok=True)
    safe_name = topic.lower().replace(" ", "_")[:30]
    filename = f"{safe_name}_{datetime.now().strftime('%Y%m%d_%H%M')}.md"
    filepath = os.path.join(REPORTS_DIR, filename)

    with open(filepath, "w", encoding="utf-8") as f:
        f.write(full_report)

    return f"Report saved to: {filepath}"
